---

- name: ensure software present (fedora)
  dnf: name={{ item }} state=present
  when: ansible_distribution == 'Fedora'
  with_items:
    - python3
    - python # default is python2
    - ruby
    - openssh
    - zsh
    - tmux
    - htop
    - offlineimap
    - ranger
    - git
    - nodejs
    - npm
    - pinentry
    - gnupg

    # python packages
    - python3-devel
    - python3-pip
    - python3-requests
    - python-devel
    - python-pip
    - python2-requests


- name: ensure software present (arch)
  pacman: name={{ item }} state=present
  when: ansible_distribution == 'Archlinux'
  with_items:
    - python
    - python2
    - ruby
    - openssh
    - zsh
    - tmux
    - htop
    - offlineimap
    - mutt
    - ranger
    - cmus
    - git
    - nodejs
    - npm
    - pinentry
    - gnupg
    - the_silver_searcher


    # python libraries
    - python-requests
    - python-pip
    - python-virtualenv
    - python-netifaces
    - python-jedi
    - python-neovim

    - python2-requests
    - python2-pip
    - python2-virtualenv
    - python2-jedi
    - python2-neovim

    # aur
    - todotxt-machine-git
    - neovim-git


- name: ensure software present (arch, graphical)
  pacman: name={{ item }} state=present
  when: ansible_distribution == 'Archlinux' and graphical_env
  with_items:
    - i3
    - copyq
    - dunst
    - udiskie
    - termite
    - rofi
    - xdotool
    - xorg-xrandr
    - xorg-xsetroot
    - arandr
    - blueberry
    - kdeconnect
    - feh
    - numlockx
    - compton
    - network-manager-applet
    - gvim
    - python2-gnomekeyring # for .offlineimap.py
    - pavucontrol
    - xorg-xbacklight

    # screenshots
    - maim
    - slop

    # aur
    - pasystray-git
    - xbanish-git
    - xcape-git
    - qutebrowser-git
    - pulseaudio-ctl


# python packages
# - name: pip software (python3)
#   pip: name={{ item }} state=latest executable=pip3
#   with_items:

- name: pip software (python3, graphical)
  pip: name={{ item }} state=latest executable=pip3
  when: graphical_env
  with_items:
    - i3pystatus
    - colour # for i3pystatus

# - name: pip software (python2)
#   pip: name={{ item }} state=latest executable=pip2
#   with_items:
#     - neovim

