# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  scm-init: git
  params:
   author-name: Samuel Walladge
   author-email: samuel@swalladge.id.au
   github-username: swalladge

save-hackage-creds: true

# stack-colors: error=31:good=32:shell=35:dir=34:recommendation=32:target=95:module=35:package-component=95

ghc-options:
  "$locals": -Wall -Werror
